### ISSUE TITLE
Structured UA - robots and aliases

### ISSUE THREAD

**Issue by patmmccann** [google/rtb-experimental#4]
Robots often don't care about their personal privacy, but want their browser to be treated as if it were Chrome or some other popular brand. For example Googlebot, Baidu, Integral Ad Science, Page Speed Insights Bot. Publishers often like knowing how often these bots come to their page by querying logs for them. It seems a browser sub-brand field could solve this. 

Similarly, Edge, Pinterest Webview, and Vivaldi browsers like to pretend to be Chrome, even while having a different feature set. Publishers often run queries to identify these users as having bad experiences in aggregate based on access log queries. This brand aliasing, 'you probably want to treat me as chrome but I am really Edge or Vivaldi' seems useful to preserve. An optional subbrand would seem to succeed in preserving this.

**Comment by sbelov** [comment]
Thank you for your interest in the Structured User Agent proposal! Let me first clarify your suggestion. In the issue, you refer to publishers querying their logs; web publishers in most cases are able to log the information they receive in HTTP requests and headers themselves. 

Is the issue referring to the user agent-related information sent via the server-to-server real-time bidding protocol used by ad tech companies to buy and sell advertising, or to the user agent information exposed by browsers in HTTP(s) headers? Structured User Agent proposal focuses on the former.

**Comment by patmmccann** [comment]
Thanks for the clarification

Browsers make client side calls to ssps with exposed user agents; this proposal only is affecting what a dsp would see?

**Comment by sbelov** [comment]
Yes, indeed; the proposal is only focused on the representation of the user agent information on the interface between SSP and DSP – in bid requests.
